### ISSUE TITLE
"Execution context was destroyed, most likely because of a navigation" when using `expect(page).to have_content` or `have_selector`

### ISSUE THREAD

**Issue by dtinth** [YusukeIwaki/capybara-playwright-driver#51]
A common pattern in testing is to do this:

```ruby
click_on 'Confirm'
expect(page).to have_content "Thank you"
```

However, `page` sometimes refers to the previous page. This resulted in an error like this:

```ruby
     Playwright::Error:
       Error: Execution context was destroyed, most likely because of a navigation
```

This is my current ugly workaround. I monkeypatched `Capybara::Session` to retry `assert_text` 3 times:

```ruby
  module Capybara::Session::PlaywrightSessionHasContentHack
    def assert_text(*args, **options)
      attempt = 0
      loop do |i|
        sleep 1 if attempt > 0
        attempt += 1
        begin
          return super
        rescue => e
          raise e if attempt > 3
          next if e.message.include?("Execution context was destroyed")
          next if e.message.include?("Cannot find context with specified id")
          raise e
        end
      end
    end
  end
  Capybara::Session.prepend(Capybara::Session::PlaywrightSessionHasContentHack)
```

**Comment by YusukeIwaki** [comment]
@dtinth  Thank you for bug report. Do you have a code for reproducing this issue?

**Comment by dtinth** [comment]
I’m feeling a bit better (and bored) so here’s a repro.

https://github.com/dtinth/capybara-playwright-driver-issue-51-repro

**Comment by dtinth** [comment]
@YusukeIwaki Thank you for the fix! 🙏  Looking forward to the new release 😃

**Comment by YusukeIwaki** [comment]
v0.3.1 is deployed.
https://rubygems.org/gems/capybara-playwright-driver/versions/0.3.1

Could you try it? Thank you, and sorry for late fix.
