### ISSUE TITLE
How do I set the screen size and screenshot size?

### ISSUE THREAD

**Issue by mhenrixon** [YusukeIwaki/capybara-playwright-driver#61]
Thanks for a phenomenal open-source project. I haven't been able to figure out how to control the screen size and the screenshot size. 

I'd love it a little bigger, and it doesn't look like the default settings for capybara or system tests does anything.

**Comment by YusukeIwaki** [comment]
@mhenrixon Could you provide an example code?

I think `resize_window_to`  would change the viewport size.

**Comment by mhenrixon** [comment]
How do i set resize_window_to?

**Comment by YusukeIwaki** [comment]
Please refer this: https://stackoverflow.com/questions/18390071/change-default-capybara-browser-window-size
`resize_window_to` is common to Selenium Driver and also available on capybara-playwright-driver.

**Comment by mhenrixon** [comment]
```ruby
Capybara.page.current_window.resize_to(2048, 1536)
```

Does the trick!
