### ISSUE TITLE
How to get console output from browser?

### ISSUE THREAD

**Issue by amkisko** [YusukeIwaki/capybara-playwright-driver#73]
Hey!
I would like to get JavaScript output from browser side to ruby.
Are there any possibilities to do so with this driver?

**Comment by YusukeIwaki** [comment]
The function is not provided by this capybara driver, however we can use https://playwright-ruby-client.vercel.app/docs/api/console_message for observing the console log output via page.

```
page.driver.with_playwright_page do |page|
  page.on("console", ->(msg) {
    if msg.type == 'error'
      puts "error: #{msg.text}"
    end
  })
end
```

Could you try it?

**Comment by amkisko** [comment]
Thank you, works perfect!

I tried it in different places, seems that the callback is correctly set only after `visit` (probably when the page has been initialised), although `page` instance and `with_playwright_page` do not raise exceptions in the other places.
