### ISSUE TITLE
#86 broke send_keys with shift plus special keys

### ISSUE THREAD

**Issue by albus522** [YusukeIwaki/capybara-playwright-driver#88]
`page.send_keys([:shift, :home])` now errors with
```
Playwright::Error:
       Unknown key: "HOME"
```

**Comment by gma** [comment]
I've got the same problem. I suspect commit 733e025e might have introduced it.

My Capybara code (that works on 0.5.2) looks like this:

```ruby
find('body').send_keys :tab, 'blue', %i[shift return], 'red', :return
```

I'm getting the following error:

```
Playwright::Error: Unknown key: "ENTER"
```

**Comment by maciesielka** [comment]
I can take a stab at fixing this, it makes sense that only character-keys should be upcased

**Comment by maciesielka** [comment]
Took a stab in https://github.com/YusukeIwaki/capybara-playwright-driver/pull/90
